// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.6.6
// Generated from `GoServant.jce'
// **********************************************************************

package main

import "C"
import "unsafe"
import "bytes"
import "taf/jce"
import "./HUYA"

//export OnDispatch4HUYAGoServant
func OnDispatch4HUYAGoServant(funcId int32, req *C.char, reqSize C.int, rsp **C.char, rspSize *C.int) int32 {
	var jis jce.JceInputStream
	jis.Reader = bytes.NewReader(C.GoBytes(unsafe.Pointer(req), reqSize))
	var jos jce.JceOutputStream
	jos.Buffer = bytes.NewBuffer(nil)

	ret := HUYA.OnDispatch4GoServant(funcId, jis, &jos)

	*rspSize = C.int(jos.Len())
	*rsp = C.CString(jos.String())

	return ret
}

func main() {}
