// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.6.6
// Generated from `ActivityRankServant.jce'
// **********************************************************************

package HUYA

// #cgo LDFLAGS: -L../ -lServantPrxGlue -lstdc++ -Wl,-rpath=./
// #cgo CFLAGS: -I../
// #include "ServantPrxGlue.h"
// #include "stdlib.h"
import "C"
import "unsafe"
import "bytes"
import "errors"
import "taf/jce"
type ActivityRankServantProxy struct {
	objName *C.char
	getRankFN *C.char
	getRankListFN *C.char
	updateRankFN *C.char
	delRankListFN *C.char
	syncCacheFN *C.char
}

func NewActivityRankServantProxy(objectName string) *ActivityRankServantProxy{
	return &ActivityRankServantProxy{
		objName: C.CString(objectName),
		getRankFN: C.CString("getRank"),
		getRankListFN: C.CString("getRankList"),
		updateRankFN: C.CString("updateRank"),
		delRankListFN: C.CString("delRankList"),
		syncCacheFN: C.CString("syncCache"),
	}
}

func DelActivityRankServantProxy(prx *ActivityRankServantProxy) {
	C.free(unsafe.Pointer(prx.objName))
	C.free(unsafe.Pointer(prx.getRankFN))
	C.free(unsafe.Pointer(prx.getRankListFN))
	C.free(unsafe.Pointer(prx.updateRankFN))
	C.free(unsafe.Pointer(prx.delRankListFN))
	C.free(unsafe.Pointer(prx.syncCacheFN))
}

func (self *ActivityRankServantProxy) getRank(tReq ActivityRankReq, tRsp *ActivityRankRsp) (ret int32, err error) {
	var jos jce.JceOutputStream
	jos.Buffer = bytes.NewBuffer(nil)
	err = jos.WriteField(&tReq,1)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	err = jos.WriteField(tRsp,2)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	reqBufSize := C.int(jos.Len())
	reqBuf := C.CString(jos.String())
	defer C.free(unsafe.Pointer(reqBuf))
	rspBufSize := C.int(0)
	var rspBuf *C.char
	defer C.free(unsafe.Pointer(rspBuf))
	iRet := C.TafInvoke4Go(self.objName, self.getRankFN, reqBuf, reqBufSize, &rspBuf, &rspBufSize)
	if iRet != 0 {
		return ret, errors.New("Failed in taf invoke.")
	}
	var jis jce.JceInputStream
	jis.Reader = bytes.NewReader(C.GoBytes(unsafe.Pointer(rspBuf), rspBufSize))
	jis.ReadField(0, true, &ret)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	jis.ReadField(2, true, tRsp)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	return ret, err
}

func (self *ActivityRankServantProxy) getRankList(tReq ActivityRankListReq, tRsp *ActivityRankListRsp) (ret int32, err error) {
	var jos jce.JceOutputStream
	jos.Buffer = bytes.NewBuffer(nil)
	err = jos.WriteField(&tReq,1)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	err = jos.WriteField(tRsp,2)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	reqBufSize := C.int(jos.Len())
	reqBuf := C.CString(jos.String())
	defer C.free(unsafe.Pointer(reqBuf))
	rspBufSize := C.int(0)
	var rspBuf *C.char
	defer C.free(unsafe.Pointer(rspBuf))

	iRet := C.TafInvoke4Go(self.objName, self.getRankListFN, reqBuf, reqBufSize, &rspBuf, &rspBufSize)
	if iRet != 0 {
		return ret, errors.New("Failed in taf invoke.")
	}

	var jis jce.JceInputStream
	jis.Reader = bytes.NewReader(C.GoBytes(unsafe.Pointer(rspBuf), rspBufSize))
	jis.ReadField(0, true, &ret)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	jis.ReadField(2, true, tRsp)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}

	return ret, err
}

func (self *ActivityRankServantProxy) updateRank(tReq UpdateActivityRankReq, tRsp *ActivityRankRsp) (ret int32, err error) {
	var jos jce.JceOutputStream
	jos.Buffer = bytes.NewBuffer(nil)
	err = jos.WriteField(&tReq,1)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	err = jos.WriteField(tRsp,2)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	reqBufSize := C.int(jos.Len())
	reqBuf := C.CString(jos.String())
	defer C.free(unsafe.Pointer(reqBuf))

	rspBufSize := C.int(0)
	var rspBuf *C.char
	defer C.free(unsafe.Pointer(rspBuf))
	iRet := C.TafInvoke4Go(self.objName, self.updateRankFN, reqBuf, reqBufSize, &rspBuf, &rspBufSize)
	if iRet != 0 {
		return ret, errors.New("Failed in taf invoke.")
	}

	var jis jce.JceInputStream
	jis.Reader = bytes.NewReader(C.GoBytes(unsafe.Pointer(rspBuf), rspBufSize))
	jis.ReadField(0, true, &ret)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	jis.ReadField(2, true, tRsp)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	return ret, err
}

func (self *ActivityRankServantProxy) delRankList(tReq DelActivityRankListReq) (ret int32, err error) {
	var jos jce.JceOutputStream
	jos.Buffer = bytes.NewBuffer(nil)
	err = jos.WriteField(&tReq,1)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	reqBufSize := C.int(jos.Len())
	reqBuf := C.CString(jos.String())
	defer C.free(unsafe.Pointer(reqBuf))
	rspBufSize := C.int(0)
	var rspBuf *C.char
	defer C.free(unsafe.Pointer(rspBuf))
	iRet := C.TafInvoke4Go(self.objName, self.delRankListFN, reqBuf, reqBufSize, &rspBuf, &rspBufSize)
	if iRet != 0 {
		return ret, errors.New("Failed in taf invoke.")
	}
	var jis jce.JceInputStream
	jis.Reader = bytes.NewReader(C.GoBytes(unsafe.Pointer(rspBuf), rspBufSize))
	jis.ReadField(0, true, &ret)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	return ret, err
}

func (self *ActivityRankServantProxy) syncCache(tReq ARSyncCacheReq) (ret int32, err error) {
	var jos jce.JceOutputStream
	jos.Buffer = bytes.NewBuffer(nil)
	err = jos.WriteField(&tReq,1)
	if err != nil {
		return jce.JCESERVERENCODEERR, err
	}
	reqBufSize := C.int(jos.Len())
	reqBuf := C.CString(jos.String())
	defer C.free(unsafe.Pointer(reqBuf))
	rspBufSize := C.int(0)
	var rspBuf *C.char
	defer C.free(unsafe.Pointer(rspBuf))
	iRet := C.TafInvoke4Go(self.objName, self.syncCacheFN, reqBuf, reqBufSize, &rspBuf, &rspBufSize)
	if iRet != 0 {
		return ret, errors.New("Failed in taf invoke.")
	}
	var jis jce.JceInputStream
	jis.Reader = bytes.NewReader(C.GoBytes(unsafe.Pointer(rspBuf), rspBufSize))
	jis.ReadField(0, true, &ret)
	if err != nil {
		return jce.JCESERVERDECODEERR, err
	}
	return ret, err
}



