// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.6.6
// Generated from `GoServant.jce'
// **********************************************************************

package HUYA

import (
	"taf/jce"
)

type TestSt struct {
	iNum int32
	sName string
}

func (self *TestSt) ResetDefault() {
	self.iNum = 0
	self.sName = ""
}

func (self *TestSt) SetiNum(val int32) {
	self.iNum = val
}

func (self *TestSt) GetiNum() int32 {
	return self.iNum
}

func (self *TestSt) SetsName(val string) {
	self.sName = val
}

func (self *TestSt) GetsName() string {
	return self.sName
}

func (self *TestSt) ReadFrom(jis *jce.JceInputStream) (err error) {
	err = jis.ReadField(0, false, &(self.iNum))
	if err != nil {
		return err
	}
	err = jis.ReadField(1, false, &(self.sName))
	if err != nil {
		return err
	}
	return err
}

func (self *TestSt) WriteTo(jos *jce.JceOutputStream) (err error) {
	err = jos.WriteField(&(self.iNum), 0)
	if err != nil {
		return err
	}
	err = jos.WriteField(&(self.sName), 1)
	if err != nil {
		return err
	}
	return err
}

type GoServant interface {
	getRankGo(tReq ActivityRankReq, tRsp *ActivityRankRsp) int32
	getRankListGo(tReq ActivityRankListReq, tRsp *ActivityRankListRsp) int32
	updateRankGo(tReq UpdateActivityRankReq, tRsp *ActivityRankRsp) int32
}



